Toolbar headline
tatouroberto/project-portfolio pull request #1
Opened 2023-07-13 18:25 UTC by tatouroberto

In this Milestone I implemented all the features for the [Portfolio-project: setup and mobile first](https://github.com/tatouroberto/portfolio-project) project, including:

Built the layout and styles for the Toolbar (header) section.
Developed the layout and styles for the Headline section.
Most elements were positioned using flexbox.

2023-07-13 20:25 UTC, shahadat3669 requested changes
Hi @tatouroberto , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! There are a few issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's ok to have bugs in your code. 🆗 Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality 💯 and help you **get a better ** 💼.

I am going to guide you on how to fix them down below. 👇 


## Highlights
✅ No linter Errors
✅ Descriptive PR Title
✅ Descriptive PR Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Thank you for your time 🙏 and call me if you need help or clarification ☎️
| GitHub | LinkedIn |  Slack |  E-Mail    |
| --- | --- | --- | --- |
|   [ ![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white) ](https://github.com/shahadat3669)   |   [ ![LinkedIn](https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white) ](https://www.linkedin.com/in/shahadat-cseng/)    |  [ ![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white) ](https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V)   |  [ ![Gmail](https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white) ](mailto:shahadat3adsf669@gmail.com?subject=Microverse%20Code%20Review)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 20:25 UTC, shahadat3669 commented on index.html
> +        <a href="" class="aa"><h2 class="logo">My logo</h2></a>
- [ ] Great job on implementing the logo within your toolbar! However, I would recommend using a different tag, such as `<div>`, `<span>`, or an appropriate tag based on the significance of the logo within your code, instead of the `<h2>` tag. This will improve user experience and conform to established conventions.

- [ ] Additionally, please adjust the spacing in the top and left side of your logo to match the design specifications. Comparing to the design, the current spacing appears to be excessive. Please update your code accordingly.

Addressing these suggestions will enhance the visual appearance, accessibility, and semantics of your toolbar. Keep up the good work! 👍🎨

2023-07-13 20:25 UTC, shahadat3669 commented on index.html
> +          <i class="fa-solid fa-bars"></i>
- [ ] Excellent work on implementing the hamburger image within your toolbar! However, to enhance the semantics and accessibility of your code, I recommend wrapping the hamburger image in a `<button>` element. These adjustments will improve the structure and meaning of your code, making it more accessible for users.
- [ ] Additionally, please adjust the spacing on your icon's top and right sides to match the design specifications. Compared to the design, the current spacing appears to be excessive. Please update your code accordingly.

Please make the necessary changes to implement the `<button>` element, ensuring a better semantic structure for your toolbar. Keep up the great work! 👍🌟

2023-07-13 20:25 UTC, shahadat3669 commented on index.html
> +        <section class="hearder-section">
- [ ] Great job on implementing all the elements in the section! However, according to the design specifications, this section should have a background image. Please review the design carefully and update your code to include the specified background image. This will help ensure that your website matches the intended visual style.
![image](https://github.com/tatouroberto/project-portfolio/assets/55840999/b58ec895-8295-4643-90df-2ca56e0d16e9)

Keep up the good work and make sure to address this adjustment to align with the design requirements! 👍🌟

2023-07-13 20:25 UTC, shahadat3669 commented on index.html
> +              <h1 class="h-title">I’m TATOU. Glad to see you!</h1>
- [ ] Well done on applying the proper font styles to the title! However, there are a couple of adjustments that need to be made:
  - [ ] Please avoid using fixed width and height for the elements on your webpage, as the project requirement emphasizes the need for a responsive website. Consider using relative units (such as percentages or `vw`/`vh`) instead of fixed values to allow your elements to adjust based on the screen size.
  - [ ] Additionally, the gap around the title does not match the design specifications. Please carefully review the design and update your code to ensure the correct spacing on all sides of the title.

Keep up the great work, and make sure to address these adjustments to achieve a responsive and visually appealing design! 👍🌟

2023-07-13 20:25 UTC, shahadat3669 commented on index.html
> +      </ul>
- [ ] Great job on using an unordered list for the social icons and including link tags for each icon! However, it seems that the icons are currently hidden visually. To ensure they are visible on the webpage, please update your code to display the icons properly according to the design.

![image](https://github.com/tatouroberto/project-portfolio/assets/55840999/f019edbb-6551-499a-ad54-c6463f21aeb8)


By addressing this issue, you will ensure that the social icons are visible and enhance the overall visual appeal of your webpage. Keep up the good work! 👍🎉

2023-07-13 20:25 UTC, shahadat3669 commented on index.html
> +      <a href="" class="connect-P">LET’S CONNECT</a>
- [ ] Well done on adding the "LET'S CONNECT" social link title! However, there are a couple of adjustments that need to be made:
  - [ ] It's important to use the appropriate heading tag (such as `<h2>` to `<h6>`) for the title instead of an "a" tag. This will ensure better semantic structure and accessibility. Please consider replacing the "a" tag with the proper heading tag in your code.
  - [ ] Additionally, the line height and font weight of the title do not match the design specifications. Please carefully review the design and update your code to match the specified line height and font weight for the title.

Making these changes will enhance the readability, organization, and visual consistency of your code. If you have any questions or need further assistance, feel free to ask. Good luck with the update! 💪🔧👍

2023-07-14 00:12 UTC, Owusu-Desmond requested changes
Hi @tatouroberto , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 00:12 UTC, Owusu-Desmond commented on style.css
> +
- [ ] From the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), But as you can see there are some differences between the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0) and your design so make sure that you add a background image to a header section to look exactly like the Figma design. :pray: 

| Your Design |Figma Design |
| :---:   | :---: | 
| ![image](https://github.com/tatouroberto/project-portfolio/assets/92303891/5cbd2446-6f98-45ea-a70c-c48f06badc75)| ![image](https://github.com/tatouroberto/project-portfolio/assets/92303891/e5ca2392-840d-4181-a21c-be8b192cbd54)|

2023-07-14 01:05 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @tatouroberto, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 15:50 UTC, merged